# Generated by Django 5.2.3 on 2025-06-24 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
    ]
